<?php

include_once('billund_tabroll.features.inc');


/**
 * Implementation of hook_imagecache_default_presets_alter().
 */
function billund_tabroll_imagecache_default_presets_alter(&$presets) {
  // Remove desaturation action from default ding_tabroll preset
  if (isset($presets['460_240_crop'])) {
    foreach ($presets['460_240_crop']['actions'] as $key => $action) {
      if ($action['action'] == 'imagecache_desaturate') {
        unset($presets['460_240_crop']['actions'][$key]);
      }
    }
  }
}